package cerror

const BAD_REQUEST = "BAD_REQUEST"
const NOT_FOUND = "NOT_FOUND"
const FORBIDDEN = "FORBIDDEN"
const INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR"

const UNSUPPORTED_FORMAT = "UNSUPPORTED_FORMAT"

const TEAMS_LIMIT = "TEAMS_LIMIT"
